# Generated by Django 5.2.18 on 2026-10-09 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='kısa ad')),
                ('name', models.CharField(max_length=100, verbose_name='ad')),
                ('is_active', models.BooleanField(default=True, verbose_name='kayıtta seçilebilir')),
            ],
            options={
                'verbose_name': 'sınav',
                'verbose_name_plural': 'sınavlar',
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='kod')),
                ('name', models.CharField(max_length=100, verbose_name='ad')),
                ('date', models.DateField(verbose_name='tarih')),
                ('date_is_estimated', models.BooleanField(default=True, verbose_name='tarih tahmini')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='süre (dk)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='sıra')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='catalog.exam', verbose_name='sınav')),
            ],
            options={
                'verbose_name': 'oturum',
                'verbose_name_plural': 'oturumlar',
                'ordering': ['exam', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ExamTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='kısa ad')),
                ('name', models.CharField(max_length=150, verbose_name='ad')),
                ('question_count', models.PositiveSmallIntegerField(verbose_name='soru sayısı')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='sıra')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='catalog.examsession', verbose_name='oturum')),
            ],
            options={
                'verbose_name': 'test',
                'verbose_name_plural': 'testler',
                'ordering': ['session', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='kısa ad')),
                ('name', models.CharField(max_length=100, verbose_name='ad')),
                ('question_count', models.PositiveSmallIntegerField(verbose_name='soru sayısı')),
                ('question_count_is_estimated', models.BooleanField(default=False, verbose_name='soru sayısı tahmini')),
                ('minutes_per_question', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='soru başına dakika (tahmini)')),
                ('group', models.CharField(choices=[('quant', 'Sayısal'), ('verbal', 'Sözel'), ('science', 'Fen'), ('social', 'Sosyal'), ('language', 'Dil')], max_length=10, verbose_name='grup')),
                ('color', models.CharField(max_length=7, verbose_name='renk (hex)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='sıra')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='catalog.examtest', verbose_name='test')),
            ],
            options={
                'verbose_name': 'ders',
                'verbose_name_plural': 'dersler',
                'ordering': ['test', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='kısa ad')),
                ('name', models.CharField(max_length=150, verbose_name='ad')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='müfredat sırası')),
                ('avg_questions', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='ortalama soru sayısı')),
                ('learn_hours', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='öğrenme süresi (saat)')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Kolay'), (2, 'Orta'), (3, 'Zor')], default=2, verbose_name='zorluk')),
                ('is_estimated', models.BooleanField(default=True, verbose_name='değerler tahmini')),
                ('source_note', models.TextField(blank=True, verbose_name='kaynak notu')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='unlocks', to='catalog.topic', verbose_name='ön koşullar')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='catalog.subject', verbose_name='ders')),
            ],
            options={
                'verbose_name': 'konu',
                'verbose_name_plural': 'konular',
                'ordering': ['subject', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='kod')),
                ('name', models.CharField(max_length=50, verbose_name='ad')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='catalog.exam', verbose_name='sınav')),
                ('tests', models.ManyToManyField(related_name='tracks', to='catalog.examtest', verbose_name='plana dahil testler')),
            ],
            options={
                'verbose_name': 'alan',
                'verbose_name_plural': 'alanlar',
                'ordering': ['exam', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(fields=('exam', 'code'), name='catalog_session_exam_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('exam', 'code'), name='catalog_track_exam_code_unique'),
        ),
    ]
