# Generated by Django 5.2.18 on 2026-10-09 15:37

import django.core.validators
import django.db.models.deletion
import planner.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_on', models.DateField(verbose_name='çözüldüğü tarih')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.examsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_exams', to=settings.AUTH_USER_MODEL)),
                ('weak_topics', models.ManyToManyField(blank=True, related_name='+', to='catalog.topic')),
            ],
            options={
                'verbose_name': 'deneme',
                'verbose_name_plural': 'denemeler',
                'ordering': ['-taken_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('onboarding', 'Tanışma'), ('phase_change', 'Dönem değişimi'), ('settings_change', 'Ayar değişikliği'), ('rescope', 'Kapsam güncellemesi'), ('levels_changed', 'Seviye değişikliği'), ('manual', 'Elle')], max_length=16)),
                ('phase_code', models.CharField(max_length=2)),
                ('days_left', models.IntegerField()),
                ('budget', models.JSONField(default=dict)),
                ('required_minutes', models.PositiveIntegerField(default=0)),
                ('coverage_ratio', models.FloatField(default=0)),
                ('projection', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'planlar',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlanTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included', models.BooleanField()),
                ('sequence', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('priority', models.FloatField(default=0)),
                ('gain', models.FloatField(default=0)),
                ('need_minutes', models.PositiveIntegerField(default=0)),
                ('reason_code', models.CharField(choices=[('selected', 'Seçildi'), ('already_good', 'Zaten iyi'), ('no_time', 'Vakit yok'), ('big_topic_late', 'Büyük konu, geç kalındı'), ('user_excluded', 'Kullanıcı çıkardı'), ('prerequisite', 'Ön koşul')], max_length=16)),
                ('start_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_topics', to='planner.plan')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.topic')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday_minutes', models.PositiveSmallIntegerField(default=120, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(600), planner.models.validate_half_hour], verbose_name='hafta içi günlük dakika')),
                ('weekend_minutes', models.PositiveSmallIntegerField(default=240, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(660), planner.models.validate_half_hour], verbose_name='hafta sonu günlük dakika')),
                ('rest_weekday', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(6)], verbose_name='dinlenme günü (0=pazartesi)')),
                ('peak_time', models.CharField(choices=[('morning', 'Sabah'), ('noon', 'Öğle'), ('evening', 'Akşam'), ('night', 'Gece')], default='morning', max_length=10, verbose_name='verimli saat')),
                ('target_department', models.CharField(blank=True, max_length=100, verbose_name='hedef bölüm')),
                ('target_tyt_net', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='hedef TYT neti')),
                ('target_ayt_net', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='hedef AYT/YDT neti')),
                ('onboarding_step', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='tanışma adımı')),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_daily_sync', models.DateField(blank=True, null=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.exam')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.track')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'öğrenci profili',
                'verbose_name_plural': 'öğrenci profilleri',
            },
        ),
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_level', models.PositiveSmallIntegerField(choices=[(0, 'Hiç bilmiyorum'), (1, 'Biraz biliyorum'), (2, 'İyiyim')], default=0)),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Hiç bilmiyorum'), (1, 'Biraz biliyorum'), (2, 'İyiyim')], default=0)),
                ('state', models.CharField(choices=[('not_started', 'Başlanmadı'), ('in_progress', 'Devam ediyor'), ('learned', 'Öğrenildi'), ('excluded', 'Kapsam dışı')], default='not_started', max_length=12)),
                ('remaining_learn_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('remaining_practice_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('learned_on', models.DateField(blank=True, null=True)),
                ('boost', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(2.0)])),
                ('questions_solved', models.PositiveIntegerField(default=0)),
                ('questions_correct', models.PositiveIntegerField(default=0)),
                ('questions_wrong', models.PositiveIntegerField(default=0)),
                ('user_override', models.CharField(blank=True, choices=[('force_include', 'Yine de ekle'), ('force_exclude', 'Çıkar')], max_length=14, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'konu ilerlemesi',
                'verbose_name_plural': 'konu ilerlemeleri',
            },
        ),
        migrations.CreateModel(
            name='MockScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.PositiveSmallIntegerField(default=0)),
                ('wrong', models.PositiveSmallIntegerField(default=0)),
                ('blank', models.PositiveSmallIntegerField(default=0)),
                ('mock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='planner.mockexam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.subject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('mock', 'subject'), name='planner_mockscore_mock_subject_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='planner_one_active_plan_per_user'),
        ),
        migrations.AddConstraint(
            model_name='plantopic',
            constraint=models.UniqueConstraint(fields=('plan', 'topic'), name='planner_plantopic_plan_topic_unique'),
        ),
        migrations.AddConstraint(
            model_name='topicprogress',
            constraint=models.UniqueConstraint(fields=('user', 'topic'), name='planner_progress_user_topic_unique'),
        ),
    ]
