# Generated by Django 5.2.18 on 2026-10-09 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('interval_index', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[('learn', 'Konu çalışması'), ('practice', 'Soru çözümü'), ('review', 'Tekrar'), ('mock', 'Deneme'), ('mock_review', 'Deneme analizi')], max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('minutes', models.PositiveSmallIntegerField()),
                ('question_target', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_peak', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('done', 'Yapıldı'), ('skipped', 'Atlandı'), ('missed', 'Kaçırıldı')], default='pending', max_length=8)),
                ('correct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('wrong', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('blank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='planner.plan')),
                ('review_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='planner.reviewitem')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.examsession')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'görev',
                'verbose_name_plural': 'görevler',
                'ordering': ['date', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='mockexam',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='planner.task'),
        ),
        migrations.AddIndex(
            model_name='reviewitem',
            index=models.Index(fields=['user', 'due_date'], name='planner_rev_user_id_39d5c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'topic'), name='planner_one_active_review_per_topic'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'date'], name='planner_tas_user_id_378080_idx'),
        ),
    ]
