# Generated by Django 5.2.18 on 2026-10-09 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_reviewitem_task_mockexam_task_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='rescope_proposal',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='rescope_snoozed_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WeeklyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('stats', models.JSONField(default=dict)),
                ('message', models.TextField(blank=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'haftalık değerlendirme',
                'verbose_name_plural': 'haftalık değerlendirmeler',
                'ordering': ['-week_start'],
                'constraints': [models.UniqueConstraint(fields=('user', 'week_start'), name='planner_review_user_week_unique')],
            },
        ),
    ]
