# Generated by Django 5.2.18 on 2026-10-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_studentprofile_rescope_proposal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='focus_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
